tests:
 - path: backend
   addbackend: true
   nobinary:   true
 - path: fs/operations
   subdir:   true
   fastlist: true
 - path: fs/sync
   subdir:   true
   fastlist: true
 - path: vfs
backends:
 # - backend:  "amazonclouddrive"
 #   remote:   "TestAmazonCloudDrive:"
 #   subdir:   false
 #   fastlist: false
 - backend:  "b2"
   remote:   "TestB2:"
   subdir:   true
   fastlist: true
 - backend:  "crypt"
   remote:   "TestCryptDrive:"
   subdir:   false
   fastlist: true
 - backend:  "crypt"
   remote:   "TestCryptSwift:"
   subdir:   false
   fastlist: false
 - backend:  "drive"
   remote:   "TestDrive:"
   subdir:   false
   fastlist: true
 - backend:  "dropbox"
   remote:   "TestDropbox:"
   subdir:   false
   fastlist: false
 - backend:  "googlecloudstorage"
   remote:   "TestGoogleCloudStorage:"
   subdir:   true
   fastlist: true
 - backend:  "hubic"
   remote:   "TestHubic:"
   subdir:   false
   fastlist: false
 - backend:  "jottacloud"
   remote:   "TestJottacloud:"
   subdir:   false
   fastlist: true
 - backend:  "onedrive"
   remote:   "TestOneDrive:"
   subdir:   false
   fastlist: false
 - backend:  "s3"
   remote:   "TestS3:"
   subdir:   true
   fastlist: true
 - backend:  "s3"
   remote:   "TestS3Minio:"
   subdir:   true
   fastlist: true
 - backend:  "s3"
   remote:   "TestS3Wasabi:"
   subdir:   true
   fastlist: true
 - backend:  "s3"
   remote:   "TestS3DigitalOcean:"
   subdir:   true
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/FsCopy
 - backend:  "s3"
   remote:   "TestS3Ceph:"
   subdir:   true
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/FsCopy
 - backend:  "s3"
   remote:   "TestS3Alibaba:"
   subdir:   true
   fastlist: true
 - backend:  "sftp"
   remote:   "TestSftp:"
   subdir:   false
   fastlist: false
 - backend:  "swift"
   remote:   "TestSwift:"
   subdir:   true
   fastlist: true
 - backend:  "swift"
   remote:   "TestSwiftCeph:"
   subdir:   true
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/FsCopy
 - backend:  "yandex"
   remote:   "TestYandex:"
   subdir:   false
   fastlist: false
 - backend:  "ftp"
   remote:   "TestFTP:"
   subdir:   false
   fastlist: false
 - backend:  "box"
   remote:   "TestBox:"
   subdir:   false
   fastlist: false
 - backend:  "qingstor"
   remote:   "TestQingStor:"
   subdir:   false
   fastlist: false
   oneonly:  true
 - backend:  "azureblob"
   remote:   "TestAzureBlob:"
   subdir:   true
   fastlist: true
 - backend:  "pcloud"
   remote:   "TestPcloud:"
   subdir:   false
   fastlist: false
 - backend:  "webdav"
   remote:   "TestWebdav:"
   subdir:   false
   fastlist: false
 - backend:  "cache"
   remote:   "TestCache:"
   subdir:   false
   fastlist: false
 - backend:  "mega"
   remote:   "TestMega:"
   subdir:   false
   fastlist: false
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/PublicLink
 - backend:  "opendrive"
   remote:   "TestOpenDrive:"
   subdir:   false
   fastlist: false
 - backend:  "union"
   remote:   "TestUnion:"
   subdir:   false
   fastlist: false
 - backend:  "koofr"
   remote:   "TestKoofr:"
   subdir:   false
   fastlist: false
 - backend:  "sia"
   remote:   "TestSia:"
   subdir:   false
   fastlist: false
